language: java
branches:
  only:
  - master
  - /^\d+\.\d+$/
jobs:
  include:
    - stage: test
      name: "OracleJDK 8"
      jdk: oraclejdk8
      script: mvn -q clean verify -Prabbitmq.local -B
    - if: type != pull_request
      name: "OpenJDK 11"
      jdk: openjdk11
      script: mvn -q clean verify -Prabbitmq.local -B
    - stage: deploy
      name: "Deploy to Sonatype's snapshots repository"
      if: type != pull_request AND env(SONATYPE_NEXUS_USERNAME) IS present
      script: bash .travis.deploy.artifacts.sh
services:
  - rabbitmq
notifications:
  email:
    recipients:
      - secure: "Vlip/VwUqMQV9zN75/14H55898nwoxEzQfB7BFvYWFSLYH73OhSO6aaqVd3zwu9Rqdqzw9dBE2Rk8YG6aYTIA+xQsw43UCrOCZrVkBSdujQ1KrCaQb2KFTJ0LsTAyQnQ5rQeT8kngGnm31CDgIultNwaHPHOewORVOr3r0TGWYM="
    on_success: always
    on_failure: always
